-- 初始化内嵌数据库
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (1, '娟娟', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (2, '潘潘', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (3, 'Jarvis', 1);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (4, 'Marcus', 1);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (5, '凤姐', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (6, '小潘老师', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (7, '小开小开', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (8, '阿荟', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (9, '英英', 0);
INSERT INTO `USER` (ID, `NAME`, `GENDER`)
VALUES (10, '小沛', 0);
