-- 初始化内嵌数据库
CREATE TABLE `T_STUDENTS`
(
    ID          INT IDENTITY,
    STUDENT_NUM INT,
    NAME        VARCHAR(64),
    SCORE       DOUBLE
);
-- 填充数据
INSERT INTO `T_STUDENTS` (ID, STUDENT_NUM, `NAME`, SCORE)
VALUES (1, 150912101, '海月', 80);
INSERT INTO `T_STUDENTS` (ID, STUDENT_NUM, `NAME`, SCORE)
VALUES (2, 150912102, '胡行', 88);
INSERT INTO `T_STUDENTS` (ID, STUDENT_NUM, `NAME`, SCORE)
VALUES (3, 150912111, '小贾', 60);
INSERT INTO `T_STUDENTS` (ID, STUDENT_NUM, `NAME`, SCORE)
VALUES (4, 150912115, '阿卜杜', 57);
INSERT INTO `T_STUDENTS` (ID, STUDENT_NUM, `NAME`, SCORE)
VALUES (5, 150912114, '族汉', 100);

